name: Build and Deploy

on:
  push:
    branches: migrate-appservice

env:
  IMAGE_REGISTRY: livereference.azurecr.io
  IMAGE_NAME: livereference.azurecr.io/livereference
  FIREBASE_SA_KEY: ${{ secrets.FIREBASE_SA_KEY }}

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ env.IMAGE_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Container Registryへのデプロイ
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} \
            --cache-from=$IMAGE_NAME:latest \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            ./app
          docker push $IMAGE_NAME:${{ github.sha }}
      - name: "AppServiceのConfigを更新"
        run: |
          FIREBASE_SA_KEY_BASE64=$(echo $FIREBASE_SA_KEY | openssl enc -e -base64)
          az webapp config appsettings set --resource-group livereferenceResourceGroup \
            --name livereference-app \
            --settings WEBSITES_PORT=3000 \
              FIREBASE_SA_KEY_BASE64="$FIREBASE_SA_KEY_BASE64" \
              DOCKER_REGISTRY_SERVER_URL=https://${{ env.IMAGE_REGISTRY }} \
              DOCKER_REGISTRY_SERVER_URERNAME=${{ secrets.REGISTRY_USERNAME }} \
              DOCKER_REGISTRY_SERVER_PASSWORD=${{ secrets.REGISTRY_PASSWORD }} \
            1>/dev/null
      - name: "AppServiceを再起動"
        run: |
          az webapp restart  --resource-group livereferenceResourceGroup \
            --name livereference-app
