name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      migrate-azure

env:
  IMAGE_NAME: livereferencecr.azurecr.io/live-reference

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ env.IMAGE_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Container Registryへのデプロイ
        run: |
            docker build -t $IMAGE_NAME:${{ github.sha }} -t $IMAGE_NAME:latest ./app
            docker push $IMAGE_NAME
